spring:
 application:
   name: microservice-reservation
 freemarker:
   enabled: false
 thymeleaf:
    cache: false

 eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    healthcheck:
      enable: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

server:
   port: 2222